# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{keydown}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Davis W. Frank"]
  s.date = %q{2010-09-07}
  s.default_executable = %q{keydown}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{dwfrank+github@infe.ws}
  s.executables = ["keydown"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rvmrc",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/keydown",
     "lib/keydown.rb",
     "lib/keydown/keydown.rb",
     "lib/keydown/slide.rb",
     "lib/keydown/slidedeck.rb",
     "spec/fixtures/with_title.md",
     "spec/keydown_spec.rb",
     "spec/slide_spec.rb",
     "spec/slidedeck_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/doc.rb",
     "tasks/jeweler.rb",
     "tasks/spec.rb",
     "templates/rocks/index.rhtml",
     "templates/rocks/slide.rhtml"
  ]
  s.homepage = %q{http://github.com/infews/keydown}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/keydown_spec.rb",
     "spec/slide_spec.rb",
     "spec/slidedeck_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

